### ISSUE TITLE
[7b] Vytvořit první dokument k prvnímu cvičení

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#11]
Vytvořit českou dokumentaci k prvnímu cvičení - základní operace s obrazem .
Dokumenty by měly být 2, tak aby to lícovalo s anglickou verzí.
Pod tímto issue vytváříte pouze první dokument (`matlab_start.md`).

**Comment by jedimik** [comment]
Rád bych se k tomuto tématu přidal :) 
Krajča Tomáš

**Comment by tesar-tech** [comment]
https://github.com/tesar-tech/zodoc/pull/20
