### ISSUE TITLE
[7 p] Translate file "Test základních znalostí 1" to English

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#15]
https://tesar-tech.github.io/zodoc/exercises/cs/test_basic_1 . Also create `solution` file. For advice see [Hello world exercise](https://tesar-tech.github.io/zodoc/exercises/en/hello_world_exercise). If you find any mistake, fix it in English version and describe it in comment.

**Comment by kulcsphu** [comment]
beru si to

**Comment by tesar-tech** [comment]
PR https://github.com/tesar-tech/zodoc/pull/19
