### ISSUE TITLE
[7 p] Translate file "Test základních znalostí 2" to English

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#16]
https://tesar-tech.github.io/zodoc/exercises/cs/test_basic_2 . Also create `solution` file. For advice see [Hello world exercise](https://tesar-tech.github.io/zodoc/exercises/en/hello_world_exercise). If you find any mistake, fix it in English version and describe it in comment.

**Comment by aassel** [comment]
Vzala bych to Assel Abzal

**Comment by tesar-tech** [comment]
Už to trvá moc dlouho..
