### ISSUE TITLE
[7 b] Přeložit a upravit dokumentaci o histogramech

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#18]
https://tesar-tech.github.io/zodoc/docs/en/histogram . Najdete-li pasáž, kterou by bylo dobré upravit, udělejte to a připište do komentáře.

**Comment by tesar-tech** [comment]
ok, už (jsi jedním z collaborators) se k tomu můžeš přiřadit sám a vyměnit `free` label za `assigned` bez mojí asistence

**Comment by gamodulon** [comment]
#27
