### ISSUE TITLE
[7 p] Create (translate) "test of basic knowledge 2018a"

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#21]
Wait for issue https://github.com/tesar-tech/zodoc/issues/17 to be approved. Add translation of exercise and solution file. How `exercise` section works is described [here](https://tesar-tech.github.io/zodoc/exercises/en/hello_world_exercise)

**Comment by Karina9510** [comment]
Vzala bych si to, Karina

**Comment by tesar-tech** [comment]
do 2. 11. 2018

**Comment by tesar-tech** [comment]
https://github.com/tesar-tech/zodoc/pull/28
