### ISSUE TITLE
[7 b] Konvoluce - klouzavý průměr

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#24]
Vytvořte soubor ve kterém bude stručně vysvětlená konvoluce za použití klouzavého průměru na jednorozměrném signálu i obraze. Uveďte názorně "papírový" příklad včetně výsledku - nejlepší by byla animace v podobě gifu. Zvolte vhodný název souboru. ¨

**Comment by Magias** [comment]
Vzal bych si to.

**Comment by tesar-tech** [comment]
ouk. Tak do středy 7.

**Comment by Magias** [comment]
0fa27f5 done

**Comment by Magias** [comment]
nejde mi pushnout commit
$ git push
remote: Permission to tesar-tech/zodoc.git denied to Magias.
fatal: unable to access 'https://github.com/tesar-tech/zodoc.git/': The requested URL returned error: 403
