### ISSUE TITLE
[7 b ] Segmentace tvarů s pomocí k-means  (zdroják k dispozici)

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#33]
Vytvořte nový soubor, který se bude vztahovat k proběhnuvšímu cvičení o práci s binárním obrazem.
Od načtení souboru (tvary.png), přes imbinarize a pak k-menas. Vysvětlete co se při k-means děje (shlukují se tvary podle velikosti). Využijte funkci `montage` pro zobrazení. Vytvořte i anglickou verzi. 
Zdrojový kód který tu uvádím je v základním stavu. Je třeba ho okomentovat, rozdělit, přejmenovat proměnné, pokud bude třeba, atd… Slouží spíše pro orientaci co a jak se dělo.

Zřete [konvence](https://github.com/tesar-tech/zodoc/blob/master/README.md)

Do 12. 11. 2018

``` matlab
%% tvray
A = imread('tvary.png');
Aa = {};
Aa{1} =A; 
Ag =imadjust( rgb2gray(A));
Aa{2} =Ag;

 Aa{3} = imbinarize(Ag,'adaptive','ForegroundPolarity','dark','Sensitivity',0.55);
%%
Aa{4} = imfill(~Aa{end},'holes');
Aa{5} = imclearborder(Aa{end});
%% 
% Aa{6} = bwareafilt(Aa{end},[1000 Inf]);

%% k means part 
reg_props = regionprops(Aa{5},'area');
areas =  cat(1,reg_props.Area);
hist(areas,30)
[indx, Centers] = kmeans(areas,3);

min_max = min([max(areas(indx==1)),max(areas(indx==2)),max(areas(indx==3)) ]);

Aa{6} = bwareafilt(Aa{5},[min_max Inf]);
%%
montage(Aa,'bordersize',[1 1],'backgroundcolor','green')

```

**Comment by medkolin** [comment]
Vzala bych si to, nejde mi se sama zapsat k isuue. Linda Medková.

**Comment by tesar-tech** [comment]
K issues se můžou přidávat jenom spolupracovníci (collaborators), přidal jsem tě do seznamu (už je to dýl), stačí jenom potvrdit. Koukni do spamu.
