### ISSUE TITLE
[7 b] Fotka s ručně psanými čísly na binární obraz

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#36]
[Zde](https://github.com/tesar-tech/zodoc/blob/master/input/media/cisla_ver.jpg) se nachází obrázek s ručně psanými čísly. Vaším úkolem je převést ho do binární reprezentace, kde bílé budou jednotlivé čísla a černé pozadí. Postup je velice podobný [postupu s tvary](https://github.com/tesar-tech/zodoc/issues/33) (bez té k-means části) . Možná přijde k užitku i binární matematická morfologie, v matlabu například funkce `imdilate` a `imerode`. Vytvořte patřičný soubor, tak jak praví [konvence](https://github.com/tesar-tech/zodoc/blob/master/README.md). Soubor vytvořte i v anglické verzi. 
Následovat bude úloha, kde se čísla vyříznou a pošlou do natrénované neuronové sítě ke klasifikaci. 
Do 13. 11. 2018

**Comment by aassel** [comment]
vzala bych to

**Comment by kulcsphu** [comment]
Well this is awkward. Mel jsem otevreny issue jeste predtim, nez se Assel prihlasila k tomu komentarem a az po self-assignu jsem si vsiml toho komentare. Mam i tak ukazat, co jsem vytvoril?

**Comment by tesar-tech** [comment]
Udělejte to oba, dneska. Každý svojí verzi, já to pak splácnu do jedné.

**Comment by kulcsphu** [comment]
#40

**Comment by aassel** [comment]
#41

**Comment by tesar-tech** [comment]
@kulcsphu u obrázků chybí jpg

**Comment by kulcsphu** [comment]
Opraveno. #43

**Comment by tesar-tech** [comment]
Ještě tam byl detail týkající se cesty. Cesta k těm číslům je normálně ve složce zodoc/input/media. Nicméně wyam (generátor stránek na kterém to frčí) funguje tak, že veme to co je ve složce input a to je vlastně root webu. Takže cesta ve složce která je zodoc/input/media je ve skutečnosti /media.. A ten /zodoc tam musí být z důvodu, že root webu je ve skutečnosti na tesar-tech.github.io/zodoc..
Pak je ještě dobré oříznout okraje tak, aby byly co nejmenší...
Tohle už upravím.
