### ISSUE TITLE
[7 b] Klasifikace kytky256 pomocí Alexnet (do 16.11.2018)

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#39]
Naučenou konvoluční neuronovou síť alexnet nechte klasifikovat ukázkový obrázek květiny. Vysvětlete výsledek klasifikace (proč je dobře nebo špatně), zobrazte nakolik si je alexnet "jistá", že klasifikace je správná a jaké jsou další třídy, za které může obrázek požadovat. 
Velice snadno najdete v dokumentaci matlabu ukázkový příklad, stačí to jen pochopit, ohnout pro květinu a vymyslet edukativní výstup, respektující [konvence](https://github.com/tesar-tech/zodoc/blob/master/README.md). Za plný počet bodů i s anglickou verzí.
Na obrázku je ve skutečnosti květ topinambury.

**Comment by jedimik** [comment]
Beru. T.K.

**Comment by jedimik** [comment]
#42

**Comment by tesar-tech** [comment]
Teď koukám, že už to bylo prolinkované hned z úvodu. To se omlouvám za zmatky.
