### ISSUE TITLE
[7 b] Segmentace květiny v HSV  barevném prostoru (do 30. 11.)

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#45]
Cílem úlohy je oddělit květinu od okolí, podobným způsobem jako s uplatněním funkce `imbinarize` na šedotónovou variantu obrázku. V HSB barevném prostoru se kytka segmentuje lépe. Je k tomu třeba pochopit jaký je vztah HSV a RGB. Doporučuji se podívat na funkci `colorThresholder` a pogůglit "HSV color picker". Dejte dohromady kód , jehož výsledkem bude cca toto: 

![image](https://user-images.githubusercontent.com/33880579/48670848-47728080-eb1f-11e8-828e-33d91f238862.png)

(to že je pozadí šedivé je důsledek další úpravy)

Nejprve vytvořte verzi dokumentu se vším všudy v jedné jazykové variantě, po schválení v druhé. Pokud si nejste jisti správností řešení nebo máte pochybnosti, komentujte zde.

**Comment by gamodulon** [comment]
#49
