### ISSUE TITLE
[7 b] Imagenet classes - vypsat třídy do kterých klasifikuje například alexnet (do 2. 12. 2018)

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#50]
"Imagenet classes" - to bude název souboru. 

Často se mi stává že potřebuji vyhledat, jestli je alexnet schopná klasifikovat do nějaké třídy nebo jaký index odpovídá jaké třídě, atd.. Tento příspěvek by měl hledání usnadnit.

Jde o vypsání všech 1000 tříd do nějaké čitelné podoby. Těchto 1000 tříd využívá ke klasifikaci například alexnet, googlenet a některé další z  https://www.mathworks.com/help/deeplearning/ug/pretrained-convolutional-neural-networks.html  (to zmiňte v příspěvku). V příspěvku bude jednoduchý popis a kód který dokáže vypsat všechny třídy včetně jejich indexů. Kód který to dokáže máte k dispozici:
 ``` matlab
net = alexnet;
%%
classNames = net.Layers(end).ClassNames;

%%
sorted_classNames = sort(classNames);

%%
class_Indexes = string(num2cell(1:1000)');
%%
str=strcat((sorted_classNames));
%%
a = strcat(class_Indexes,repmat(":",1000, 1),str);

%%
```

Kód upravte, vhodně okomentujte, změňte názvy proměnných, atd...
Na konci příspěvku bude vypsáno všech 1000 tříd.

Součástí úlohy je pochopení co kód dělá, seznámení se zmíněnými pojmy, atd.
Respektujte konvence, nejdřív jednu mutaci, posléze druhou.

**Comment by jedimik** [comment]
Beru

**Comment by jedimik** [comment]
#51
