### ISSUE TITLE
[5 b] Překlad Super resolution na nové verzi (do 9.12.2018)

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#54]
Přeložte tento [dokument ](https://zodoc.netlify.com/posts/en/increase_image_resolution_with_cnn) do čj na nové verzi zodocu. Tato verze aktuálně běží z větve `develop`, musíte si pullnout tu.  Podívejte se na anglický dokument a podle toho udělejte českou mutaci. Nepřekládejte `prerequisites` a `Tags`.

**Comment by srtrakka1** [comment]
Beru si to

**Comment by tesar-tech** [comment]
PR: https://github.com/tesar-tech/zodoc/pull/55 
Fajn, 
jenom nadpis taky přeložit (teď už to dotáhnu).
