### ISSUE TITLE
[7 b] Generování náhodných trojúhelníků - do 16. 12. 2018

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#58]
Pozměňte soubor vznikající zde: https://github.com/tesar-tech/zodoc/issues/57 tak aby dokázal generovat i náhodné trojúhelníky, Předem si to můžete připravit (tady nechat okomentovat) a PR vytvořit až bude předchozí  issue dokonáno

**Comment by srtrakka1** [comment]
beru si to

**Comment by tesar-tech** [comment]
Jenom ještě detail. Možná docela podstatný. Ty trojúhelníky by měly být "hezké". Tedy vyvaruj se příliš dlouhých "nudliček". Neměly by být všechny pravoúhlé a rovnostranné. Prostě aby vypadaly náhodně.

**Comment by tesar-tech** [comment]
Přidělej to semka: https://zodoc.netlify.com/posts/en/creating_an_image_set_with_various_shapes +1 b za develop.
