### ISSUE TITLE
[7 +1 b] Transfer learning do (16. 11. 2018)

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#59]
Využijte tvarů získaných zde: https://github.com/tesar-tech/zodoc/issues/57 pro přeučení neuronové sítě k jejich klasifikaci. Přibližně to co proběhlo na cvičení.

**Comment by Karina9510** [comment]
Vezmu si to

**Comment by tesar-tech** [comment]
Taky +1b pokud to bude do develop větve

**Comment by tesar-tech** [comment]
Pracuj s databází vytvořenou zde: https://zodoc.netlify.com/posts/en/creating_an_image_set_with_various_shapes

**Comment by Karina9510** [comment]
@tesar-tech, prosim te, vypada to tak ze nemam prava na pushovani do developeru na server
`C:\zodoc>git log
commit ba50dded590534678f73659ef29786a71a95fa0e (HEAD -> develop)
Author: Karina Bykovskaia <carina9510@gmail.com>
Date:   Thu Jan 3 22:21:49 2019 +0100

    Transfer_learning_Karina

C:\zodoc>git push
remote: Permission to tesar-tech/zodoc.git denied to Karina9510.
fatal: unable to access 'https://github.com/tesar-tech/zodoc.git/': The requested URL returned error: 403
`

**Comment by Karina9510** [comment]
#71
