### ISSUE TITLE
[7 b] Barevné kanály (do 5.1.2019)

### ISSUE THREAD

**Issue by tesar-tech** [tesar-tech/zodoc#65]
Toto issue je součástí předělávky do nové struktury. Vezměte soubor matlab_start (https://tesar-tech.github.io/zodoc/docs/cs/matlab_start) a z části `Zobrazit jednotlivé barevné kanály` vytvořte jeden soubor s názvem `split_and_display_channels_of_color_image.md`. Se všemi potřebnými metadaty (inspirujte se v jiných souborech). + Vysvětlete proč jsou jednotlivé obrázky kanálů šedotónové, když jsou to kanály barevné...Na větvi develop. Výsledné zobrazení udělejte pomocí funkce montage. 
Nejprve jednu jazykovou verzi, po kontrole druhou.

**Comment by Karina9510** [comment]
#71
